### PR TITLE
Added support for Ledvance (the new name for Osram lighting) GU10 bulbs

### PR DESCRIPTION
**Pull request by Joozt**
Tested with 2 GU10 bulbs that I have.

### CODE REVIEW

**Comment by RobinBol** [comment]
Thanks for your PR, in general we allow only devices of one manufacturer per app, in this case I think it is best to create a separate app for the Ledvance manufacturer. This also helps users find the devices they are looking for in the app store.

**Comment by Joozt** [comment]
Ledvance is the _internal_ name that Osram now uses for these connected lamps. The outside and the package still show the Osram brand. This is a picture of the package of the lamp that I bought:
image


It is similar to what Philips does with the Signify name. It is invisible to the user that these lamps are Ledvance branded. It would be confusing to the user if they would have to use a different app.

**Comment by RobinBol** [comment]
Ah, that was not clear to me. If it is just an internal name I suggest removing the reference to Ledvance from the readme, this would only cause confusion since regular users would never see the Ledvance product name.

**Comment by RobinBol** [comment]
Thanks for your contribution!

**Comment by Sejkooz** [comment]
Well done, how about Osram Smart + outdoor plug?

**Comment by RobinBol** [comment]
@Sejkooz if you have the device you can contact our support department with the device/product ids (see device settings), or create a PR yourself (with a new driver for the outdoor plug).

**Pull request merged**
